fix: create home directory for docker user
After the previous commit, I had run the scheduled pipeline manually,
but it failed due to the following error:

error: could not lock config file /home/maid/.gitconfig: No such file or directory

Seems we need to create the home directory as part of the Docker image.